"""empty message

Revision ID: b5f19aad7a39
Revises: 
Create Date: 2017-11-27 16:42:33.677775

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b5f19aad7a39'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auth_user', 'address',
               existing_type=mysql.VARCHAR(length=192),
               nullable=True)
    op.alter_column('auth_user', 'contact',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('auth_user', 'gender',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auth_user', 'gender',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('auth_user', 'contact',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('auth_user', 'address',
               existing_type=mysql.VARCHAR(length=192),
               nullable=False)
    # ### end Alembic commands ###
