"""empty message

Revision ID: f3ce47948dad
Revises: 
Create Date: 2017-11-18 16:25:01.449746

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f3ce47948dad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_user', 'status')
    op.drop_column('auth_user', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user', sa.Column('role', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False))
    op.add_column('auth_user', sa.Column('status', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
